line-length = 100
target-version = "py310"

# Combined excludes from .black, .flake8, and .isort.cfg skip_glob
exclude = [
    ".eggs/",
    ".git/",
    ".mypy_cache/",
    ".venv/",
    ".circleci/",
    ".vscode/",
    ".env/",
    ".coverage/",
    "build/",
    "dist/",
    "docs/",
    "locale/",
    "alembic/",
    "alembic.ini",
    "__pycache__/",
    "*.venv"
]

[lint]
# Flake8 ignores based on .flake8
# E402: module level import not at top of file
# E226: missing whitespace around arithmetic operator
# E501: line too long (handled by formatter)
ignore = ["E402", "E226", "E501"]
extend-select = ["I"]

[lint.isort]
order-by-type = false
# Based on .isort.cfg and .flake8 application settings
#known-first-party = ["app", "config"]
#known-third-party = ["scripts", "tests", "cleverea_*"]

section-order = [
  "future",
  "standard-library",
  "third-party",
  "fastapi",
  "first-party",
  "local-folder"
]
[lint.isort.sections]
"fastapi" = ["fastapi"]

[format]
# Based on .black settings and existing ruff.toml
quote-style = "double"
indent-style = "space"
# Corresponds to include_trailing_comma=True in .isort.cfg
skip-magic-trailing-comma = false
# skip-string-normalization = false is the default for Ruff formatter